version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tools/apache-tomcat-8.5.75/webapps/music
    
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 350
      runas: root

 